package dev.bosco.deskpanel;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * The payload description, read from the file the <em>server</em> writes.
 *
 * <p>T10.1. {@link DataPayload#merge} rebuilds the payload key by key, so a
 * key added on the PC and not here never reaches the phone — silently, with a
 * correct server and a correct page. That shipped twice: {@code night} in
 * T6.4 and {@code actions} in T8.2, the second time with a comment in
 * {@code DataPayload} warning about the first. A comment is not a gate.
 *
 * <p>So the shape stops being a string literal in this directory.
 * {@code server/tests/test_payload_contract.py} generates
 * {@code server/tests/fixtures/payload.json} from the server's own assembly,
 * and these tests assert against that. Add a key on the PC, regenerate, and
 * the Android suite goes red at the point of the change instead of the panel
 * losing a feature in silence.
 *
 * <p><b>The path is relative to the module directory</b>, which is where
 * Gradle runs a {@code Test} task from, and the same place
 * {@code assets.srcDirs("../../web")} counts from in {@code build.gradle.kts}.
 * If that ever changes this fails loudly with the absolute path it tried,
 * which is the point: a fixture that could not be found must never read as a
 * test with nothing to say.
 */
final class Contract {

    private static final String PAYLOAD = "../../server/tests/fixtures/payload.json";
    private static final String ACTIONS = "../../server/tests/fixtures/action_ids.json";

    // The file's bytes, read once per path. The *text* is cached and not the
    // JSONObject: every accessor below hands its object to a caller that may
    // put or remove keys on it, and a shared parse would let one test's
    // variant leak into the next.
    private static final Map<String, String> TEXT = new HashMap<>();

    private Contract() {
    }

    private static JSONObject read(String relative) {
        String text = TEXT.computeIfAbsent(relative, Contract::slurp);
        try {
            return new JSONObject(text);
        } catch (JSONException e) {
            // The file is generated by a test that also asserts its shape, so
            // a malformed one is a broken repository rather than a case a
            // caller should be made to handle. Unchecked, so every test method
            // here stays readable.
            throw new AssertionError("the payload description is not JSON: " + relative, e);
        }
    }

    private static String slurp(String relative) {
        Path path = Paths.get(relative);
        if (!Files.isRegularFile(path)) {
            throw new AssertionError(
                    "the payload description is missing: " + path.toAbsolutePath()
                    + " \u2014 generate it with DESK_PANEL_WRITE_FIXTURES=1 python -m unittest "
                    + "server.tests.test_payload_contract");
        }
        try {
            return new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static JSONObject section(String name) {
        try {
            return read(PAYLOAD).getJSONObject(name);
        } catch (JSONException e) {
            throw new AssertionError("the payload description has no `" + name + "` half", e);
        }
    }

    /** The {@code /quotes} body the server sends, exactly as it sends it. */
    static String quotes() {
        return section("quotes").toString();
    }

    /** The {@code /weather} body, still carrying its own {@code stale}. */
    static String weather() {
        return section("weather").toString();
    }

    /**
     * Every top-level key of the {@code /quotes} body.
     *
     * <p>In no particular order — {@code JSONObject} is hash-ordered, and the
     * callers loop over this rather than index into it.
     */
    static List<String> serverKeys() {
        List<String> keys = new ArrayList<>();
        for (Iterator<String> it = section("quotes").keys(); it.hasNext(); ) {
            keys.add(it.next());
        }
        return keys;
    }

    /** The catalogue {@code server/actions.py} holds, for the allowlist to match. */
    static List<String> actionIds() {
        List<String> ids = new ArrayList<>();
        try {
            JSONArray raw = read(ACTIONS).getJSONArray("catalogue");
            for (int i = 0; i < raw.length(); i++) {
                ids.add(raw.getString(i));
            }
        } catch (JSONException e) {
            throw new AssertionError("the action description has no `catalogue` list", e);
        }
        return ids;
    }

    /**
     * The quotes body with one key set \u2014 a newer PC, or a different config.
     *
     * <p>Built through {@code org.json} rather than by string surgery on the
     * fixture. The tests here used to splice text into a literal, which works
     * only while the literal's formatting is what somebody typed; a generated
     * file is free to change its spacing and would have turned every one of
     * those into a no-op that still passed.
     */
    static String quotesWith(String key, Object value) {
        return with(section("quotes"), key, value);
    }

    /** The weather body with one key set. */
    static String weatherWith(String key, Object value) {
        return with(section("weather"), key, value);
    }

    private static String with(JSONObject body, String key, Object value) {
        try {
            return body.put(key, value).toString();
        } catch (JSONException e) {
            throw new AssertionError("could not set `" + key + "`", e);
        }
    }

    /** The quotes body with keys removed \u2014 an older PC that never sent them. */
    static String quotesWithout(String... keys) {
        JSONObject body = section("quotes");
        for (String key : keys) {
            body.remove(key);
        }
        return body.toString();
    }
}
